feat: Add new variable for allowing ECR image sharing to lambda service in external account
terraform-aws-modules/terraform-aws-ecr pull request #16
Opened 2023-02-15 08:35 UTC by thepoppingone

This is extensible to other services like codebuild, however I only require lambda image to be shared to the lambda service of another for now

## Description
Introduce another variable to allow ARN of lambda functions ARNs to be stated

## Motivation and Context
Currently, the module hard codes the principal value to "AWS" only. Hence I am not able to use it for other services despite this option of inserting services to be included the policy statement being present in the AWS console
More docs here:
https://aws.amazon.com/blogs/compute/introducing-cross-account-amazon-ecr-access-for-aws-lambda/

Also this module consolidates all statements into a single policy, I cannot work around it but to add to it to handle for lambda case instead.

## Breaking Changes
None

## How Has This Been Tested?
It uses a variable with a default value of [] that will not trigger the dynamic statement

2023-02-15 11:54 UTC, antonbabenko requested changes
Looks good, but please revert unnecessary changes to files in the `.github` folder.

2023-02-15 12:03 UTC, bryantbiggs commented on main.tf
> +    for_each = var.repository_type == "private" && var.repository_lambda_read_access_arns != [] ? [1] : []
```suggestion
    for_each = var.repository_type == "private" && length(var.repository_lambda_read_access_arns) > 0 ? [1] : []
```

2023-02-16 06:48 UTC, thepoppingone commented
![image](https://user-images.githubusercontent.com/7760361/219289309-53051cbf-47d1-42f1-901d-4ed9f6fd0386.png)

2023-02-16 11:02 UTC, antonbabenko approved these changes

2023-02-16 11:02 UTC, merged

2023-02-16 11:03 UTC, antonbabenko commented
This PR is included in version 1.6.0 :tada: