Feature - Adding credentials_arn for aws_ecr_pull_through_cache_rule
terraform-aws-modules/terraform-aws-ecr pull request #30
Opened 2024-03-12 15:31 UTC by JoseAlvarezSonos

## Description

This feature PR adds the ability to pass a credentials_arn to the registry_pull_through_cache_rules variable, to allow to use this new field for pull through caches. 

## Motivation and Context

Since [November 2023](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/), ECR supports new upstream registries as pull through cache, including Dockerhub and GHCR. To use these new upstream registries, it's required to use credentials for the respective registries. AWS added a feature of providing a Secret Manager resource ARN to the ECR pull through cache rule to rely on this credentials. Along side this, the [terraform-provider-aws added the same capabilities ](https://github.com/hashicorp/terraform-provider-aws/issues/34466)to the aws_ecr_pull_through_cache_rule resource.

## Breaking Changes

This requires an update of the aws provider to >= 5.37 (previously >= 4.20). But there isn't any breaking change to update to this version.

## How Has This Been Tested?

- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

We are using our fork to make sure that it works and added all the required docs and examples to this repo as well.

2024-03-14 09:10 UTC, shivanand-deriv commented
+1

2024-03-15 11:25 UTC, antonbabenko requested changes
Looks good, but there are some minor improvements to be done.

2024-03-15 11:25 UTC, antonbabenko commented on examples/complete/main.tf
> +  dynamic "statement" {
Could you please rewrite this as two simple `statement` blocks instead of using `dynamic` in the example?

2024-03-15 11:25 UTC, antonbabenko commented on examples/complete/main.tf
> +      credential_arn = "arn:aws:secretsmanager:us-east-1:123456789:secret:ecr-pullthroughcache/dockerhub"
Let's create the Secret Manager resource using [this module](https://github.com/terraform-aws-modules/terraform-aws-secrets-manager/#standard) and pass it as a reference here to show the completely working example.

2024-03-15 11:25 UTC, antonbabenko commented on examples/complete/main.tf
> +      resources = ["arn:aws:ecr:us-east-1:012345678901:repository/${statement.value}/*"]
`012345678901` - should we replace this one with something else (more correct)?

2024-03-17 22:40 UTC, JoseAlvarezSonos commented on examples/complete/main.tf
> +  dynamic "statement" {
Yes, refactored

2024-03-17 22:41 UTC, JoseAlvarezSonos commented on examples/complete/main.tf
> +      credential_arn = "arn:aws:secretsmanager:us-east-1:123456789:secret:ecr-pullthroughcache/dockerhub"
Yes, I created the resource and added the secret_string as variable, let me know if that's ok

2024-03-17 22:41 UTC, JoseAlvarezSonos commented on examples/complete/main.tf
> +      resources = ["arn:aws:ecr:us-east-1:012345678901:repository/${statement.value}/*"]
Good observation, I replaced it with data.aws_caller_identity.current.account_id

2024-03-25 12:35 UTC, bryantbiggs approved these changes
thank you

cc @antonbabenko

2024-03-25 14:15 UTC, antonbabenko requested changes
I think AWS partition should still be fetched from data source to work for govcloud and China. The rest looks good.

2024-03-25 14:28 UTC, bryantbiggs commented
for the example? we don't usually enforce this for examples and just stick with the default commercial regions. the module source code we absolutely use the data sources to infer the correct partition, region, etc.

2024-03-25 14:53 UTC, antonbabenko commented
@bryantbiggs I looked in the wrong place :) Approved now

2024-03-25 14:54 UTC, merged

2024-03-25 14:54 UTC, antonbabenko commented
This PR is included in version 2.1.0 :tada: