Add a new variable to control the creation of a lifecycle policy
terraform-aws-modules/terraform-aws-ecr pull request #4
Opened 2022-06-11 21:50 UTC by phr3nzii

## Description
This pull request adds a new variable that determines whether a lifecycle policy is created. The previous default behaviour was to always create a lifecycle policy. If you didn't want a lifecycle policy, there was no way to do this. You will now have to set `create_lifecycle_policy` to `true` if you want a lifecycle policy to be created.

This is my first PR so apologies if I have done something wrong!

## Motivation and Context
Sometimes a lifecycle policy isn't needed or wanted. This fixes https://github.com/terraform-aws-modules/terraform-aws-ecr/issues/2 

## Breaking Changes

I wouldn't call this a breaking change. However, users who do want to have a lifecycle policy created will need to add the new variable to ensure that it is created.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

I have tested using the complete example by setting `create_lifecycle_policy` to both `true` and `false`. I've also updated this example to ensure that the lifecycle policy is created in future.

I also tested this using the reproduction code from https://github.com/terraform-aws-modules/terraform-aws-ecr/issues/2

2022-06-12 00:08 UTC, bryantbiggs requested changes

2022-06-12 00:08 UTC, bryantbiggs commented on variables.tf
> +  default     = false
To be backwards compatible, can we default to `true`

```suggestion
  default     = true
```

2022-06-13 17:07 UTC, bryantbiggs commented on wrappers/main.tf
> +  create_lifecycle_policy                   = try(each.value.create_lifecycle_policy, var.defaults.create_lifecycle_policy, false)
```suggestion
  create_lifecycle_policy                   = try(each.value.create_lifecycle_policy, var.defaults.create_lifecycle_policy, true)
```

2022-06-13 17:17 UTC, bryantbiggs approved these changes
Thanks for the changes @phr3nzii !

2022-06-13 17:17 UTC, merged

2022-06-13 17:17 UTC, antonbabenko commented
This PR is included in version 1.3.0 :tada: