feat: Add support for aws_ecr_repository_creation_template
terraform-aws-modules/terraform-aws-ecr pull request #45
Opened 2024-08-14 21:14 UTC by jakubmatyszewski

## Description
Add support for aws_ecr_repository_creation_template

## Motivation and Context
aws_ecr_repository_creation_template was added in terraform aws provider [5.61](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.61.0).

## Breaking Changes
- no

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2024-08-16 19:27 UTC, antonbabenko requested changes

2024-08-16 19:27 UTC, antonbabenko commented on examples/complete/main.tf
> +  # Registry Replication Configuration
```suggestion
  # Registry Creation Template
```

2024-08-16 19:27 UTC, antonbabenko commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2024-08-16 19:27 UTC, antonbabenko commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2024-08-16 19:27 UTC, antonbabenko commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2024-08-16 19:37 UTC, bryantbiggs requested changes
just putting a hold on this since theres quite a bit we'll need to change - most likely this resource will live in its own sub-module

the ECR team has asked me to take a look - will get to this next week

2024-09-02 14:04 UTC, amontalban commented
Hey @bryantbiggs, just checking in to see if you are working on this feature because we are about to set multiple ECR repositories and will benefit from this. Thanks in advance!

2024-09-03 13:31 UTC, bryantbiggs commented
working on it this morning as we speak - should know more about rough ETA later today

2024-09-04 00:25 UTC, bryantbiggs commented
need to revisit tomorrow with fresh eyes but you can take a look here - happy for any early feedback https://github.com/terraform-aws-modules/terraform-aws-ecr/pull/46

2024-09-04 05:28 UTC, jakubmatyszewski commented
closing this PR, thanks @bryantbiggs for taking over

2024-09-04 05:28 UTC, closed without merging